# not required, just used in the default templates
name: My Story

# also not required, just used in the default templates
defaults:
  title: Title Page

# directory holding pages (required)
src: pages
# extension of pages in src (not required, .html is default)
ext: .html 

# folder to put processed pages (required)
dest: dest
# extension of processed pages (not required, .html is default)
newext: .html

# list of templates (required)
templates:
# name of template; used to distinguish it from others in command line parameter (required)
- name: web
# location of template (required)
  location: template.html
- name: print
  location: print.html    

# list of directories to copy into dest; usually static files such as css (not required)
transfer:
- static

# a directory to search for more hooks in; added to sys.path (not required) 
hooksdir: hooks
# a list of hooks (extensions) in the form of module.class (not required)
#hooks:
# these are some random handy hooks that you may want to uncomment along with the above line
# creates a .htaccess file in dest for you that makes the directory index file the first page.
#- sandvich.hooks.HtaccessIndex
# runs pages through markdown. highly recommended because markdown is awesome, but requires python-markdown
#- sandvich.hooks.Markdown
# creates a table of contents for you among other things. you will have to modify some templates to make this work
#- sandvich.hooks.Toc

# the list of pages in order (required)
pages :
- name: title
# name of the page; used to find it in src (required)
- name: chapter1
# title of the page; a good idea (not required)
  title: Chapter One
- name: chapter2
  title: Chapter Two
